import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Datenschutzerklärung",
  description:
    "Datenschutzerklärung von online-agency.ai – Informationen zur Erhebung, Verarbeitung und Nutzung personenbezogener Daten gemäß DSGVO und TDDDG.",
  alternates: { canonical: "/datenschutz" },
  robots: { index: true, follow: true },
};

export default function DatenschutzPage() {
  return (
    <main>
      <div className="mx-auto max-w-4xl px-4 pb-24 pt-32 sm:px-6 sm:pt-36 lg:px-8">
        {/* Titel */}
        <div className="border-b border-white/10 pb-6">
          <h1 className="font-mono text-3xl font-bold tracking-tight text-white sm:text-4xl">Datenschutzerklärung</h1>
        </div>

<section id="auf-einen-blick" className="mt-16 scroll-mt-28">
<h2 className="font-mono text-2xl font-semibold text-signal-400">1. Datenschutz auf einen Blick</h2>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Allgemeine Hinweise</h3>
<p className="leading-relaxed text-white/60">Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können. Ausführliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgeführten Datenschutzerklärung.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Datenerfassung auf dieser Website</h3>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Wer ist verantwortlich für die Datenerfassung auf dieser Website?</h4>
<p className="leading-relaxed text-white/60">Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten können Sie dem Abschnitt „Hinweis zur verantwortlichen Stelle“ in dieser Datenschutzerklärung entnehmen.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Wie erfassen wir Ihre Daten?</h4>
<p className="leading-relaxed text-white/60">Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z. B. um Daten handeln, die Sie in ein Kontaktformular eingeben.</p>
<p className="mt-4 leading-relaxed text-white/60">Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z. B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Wofür nutzen wir Ihre Daten?</h4>
<p className="leading-relaxed text-white/60">Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden. Sofern über die Website Verträge geschlossen oder angebahnt werden können, werden die übermittelten Daten auch für Vertragsangebote, Bestellungen oder sonstige Auftragsanfragen verarbeitet.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Welche Rechte haben Sie bezüglich Ihrer Daten?</h4>
<p className="leading-relaxed text-white/60">Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung oder Löschung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, können Sie diese Einwilligung jederzeit für die Zukunft widerrufen. Außerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu.</p>
<p className="mt-4 leading-relaxed text-white/60">Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit an uns wenden.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Analyse-Tools und Tools von Drittanbietern</h3>
<p className="leading-relaxed text-white/60">Beim Besuch dieser Website kann Ihr Surf-Verhalten statistisch ausgewertet werden. Das geschieht vor allem mit sogenannten Analyseprogrammen.</p>
<p className="mt-4 leading-relaxed text-white/60">Detaillierte Informationen zu diesen Analyseprogrammen finden Sie in der folgenden Datenschutzerklärung.</p>
</section>
<section id="hosting" className="mt-16 scroll-mt-28 border-t border-white/10 pt-12">
<h2 className="font-mono text-2xl font-semibold text-signal-400">2. Hosting</h2>
<p className="leading-relaxed text-white/60">Wir hosten die Inhalte unserer Website bei folgendem Anbieter:</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Externes Hosting</h3>
<p className="leading-relaxed text-white/60">Diese Website wird extern gehostet. Die personenbezogenen Daten, die auf dieser Website erfasst werden, werden auf den Servern des Hosters / der Hoster gespeichert. Hierbei kann es sich v. a. um IP-Adressen, Kontaktanfragen, Meta- und Kommunikationsdaten, Vertragsdaten, Kontaktdaten, Namen, Websitezugriffe und sonstige Daten, die über eine Website generiert werden, handeln.</p>
<p className="mt-4 leading-relaxed text-white/60">Das externe Hosting erfolgt zum Zwecke der Vertragserfüllung gegenüber unseren potenziellen und bestehenden Kunden (Art. 6 Abs. 1 lit. b DSGVO) und im Interesse einer sicheren, schnellen und effizienten Bereitstellung unseres Online-Angebots durch einen professionellen Anbieter (Art. 6 Abs. 1 lit. f DSGVO). Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Unser(e) Hoster wird bzw. werden Ihre Daten nur insoweit verarbeiten, wie dies zur Erfüllung seiner Leistungspflichten erforderlich ist und unsere Weisungen in Bezug auf diese Daten befolgen.</p>
<p className="mt-4 leading-relaxed text-white/60">Wir setzen folgende(n) Hoster ein:</p>
<p className="mt-4 leading-relaxed text-white/60">Name des Anbieters: Vercel Inc.<br /> Adresse: 440 N Barranca Ave #4133, Covina, CA 91723, USA<br /> Website: <a href="https://vercel.com" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://vercel.com</a><br /> Datenschutzerklärung von Vercel: <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://vercel.com/legal/privacy-policy</a></p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Auftragsverarbeitung</h4>
<p className="leading-relaxed text-white/60">Wir haben einen Vertrag über Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>
</section>
<section id="allgemeine-hinweise" className="mt-16 scroll-mt-28 border-t border-white/10 pt-12">
<h2 className="font-mono text-2xl font-semibold text-signal-400">3. Allgemeine Hinweise und Pflichtinformationen</h2>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Datenschutz</h3>
<p className="leading-relaxed text-white/60">Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.</p>
<p className="mt-4 leading-relaxed text-white/60">Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. Die vorliegende Datenschutzerklärung erläutert, welche Daten wir erheben und wofür wir sie nutzen. Sie erläutert auch, wie und zu welchem Zweck das geschieht.</p>
<p className="mt-4 leading-relaxed text-white/60">Wir weisen darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Hinweis zur verantwortlichen Stelle</h3>
<p className="leading-relaxed text-white/60">Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:</p>
<p className="mt-4 leading-relaxed text-white/60">online-agency.ai<br /> Jan Jäger<br /> Stieglesfeld 13<br /> 72401 Haigerloch</p>
<p className="mt-4 leading-relaxed text-white/60">Telefon: +49 7474 95 46 880<br /> E-Mail: <a href="mailto:kontakt@online-agency.ai" className="text-signal-400 hover:text-signal-300 hover:underline">kontakt@online-agency.ai</a></p>
<p className="mt-4 leading-relaxed text-white/60">Verantwortliche Stelle ist die natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z. B. Namen, E-Mail-Adressen o. Ä.) entscheidet.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Speicherdauer</h3>
<p className="leading-relaxed text-white/60">Soweit innerhalb dieser Datenschutzerklärung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für die Datenverarbeitung entfällt. Wenn Sie ein berechtigtes Löschersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gelöscht, sofern wir keine anderen rechtlich zulässigen Gründe für die Speicherung Ihrer personenbezogenen Daten haben (z. B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die Löschung nach Fortfall dieser Gründe.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung auf dieser Website</h3>
<p className="leading-relaxed text-white/60">Sofern Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 9 Abs. 2 lit. a DSGVO, sofern besondere Datenkategorien nach Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdrücklichen Einwilligung in die Übertragung personenbezogener Daten in Drittstaaten erfolgt die Datenverarbeitung außerdem auf Grundlage von Art. 49 Abs. 1 lit. a DSGVO. Sofern Sie in die Speicherung von Cookies oder in den Zugriff auf Informationen in Ihr Endgerät (z. B. via Device-Fingerprinting) eingewilligt haben, erfolgt die Datenverarbeitung zusätzlich auf Grundlage von § 25 Abs. 1 TDDDG. Die Einwilligung ist jederzeit widerrufbar. Sind Ihre Daten zur Vertragserfüllung oder zur Durchführung vorvertraglicher Maßnahmen erforderlich, verarbeiten wir Ihre Daten auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren verarbeiten wir Ihre Daten, sofern diese zur Erfüllung einer rechtlichen Verpflichtung erforderlich sind, auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Die Datenverarbeitung kann ferner auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen. Über die jeweils im Einzelfall einschlägigen Rechtsgrundlagen wird in den folgenden Absätzen dieser Datenschutzerklärung informiert.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Hinweis zur Datenweitergabe in datenschutzrechtlich nicht sichere Drittstaaten sowie die Weitergabe an US-Unternehmen, die nicht DPF-zertifiziert sind</h3>
<p className="leading-relaxed text-white/60">Wir verwenden unter anderem Tools von Unternehmen mit Sitz in datenschutzrechtlich nicht sicheren Drittstaaten sowie US-Tools, deren Anbieter nicht nach dem EU-US-Data Privacy Framework (DPF) zertifiziert sind. Wenn diese Tools aktiv sind, können Ihre personenbezogene Daten in diese Staaten übertragen und dort verarbeitet werden. Wir weisen darauf hin, dass in datenschutzrechtlich unsicheren Drittstaaten kein mit der EU vergleichbares Datenschutzniveau garantiert werden kann.</p>
<p className="mt-4 leading-relaxed text-white/60">Wir weisen darauf hin, dass die USA als sicherer Drittstaat grundsätzlich ein mit der EU vergleichbares Datenschutzniveau aufweisen. Eine Datenübertragung in die USA ist danach zulässig, wenn der Empfänger eine Zertifizierung unter dem „EU-US Data Privacy Framework“ (DPF) besitzt oder über geeignete zusätzliche Garantien verfügt. Informationen zu Übermittlungen an Drittstaaten einschließlich der Datenempfänger finden Sie in dieser Datenschutzerklärung.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Empfänger von personenbezogenen Daten</h3>
<p className="leading-relaxed text-white/60">Im Rahmen unserer Geschäftstätigkeit arbeiten wir mit verschiedenen externen Stellen zusammen. Dabei ist teilweise auch eine Übermittlung von personenbezogenen Daten an diese externen Stellen erforderlich. Wir geben personenbezogene Daten nur dann an externe Stellen weiter, wenn dies im Rahmen einer Vertragserfüllung erforderlich ist, wenn wir gesetzlich hierzu verpflichtet sind (z. B. Weitergabe von Daten an Steuerbehörden), wenn wir ein berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO an der Weitergabe haben oder wenn eine sonstige Rechtsgrundlage die Datenweitergabe erlaubt. Beim Einsatz von Auftragsverarbeitern geben wir personenbezogene Daten unserer Kunden nur auf Grundlage eines gültigen Vertrags über Auftragsverarbeitung weiter. Im Falle einer gemeinsamen Verarbeitung wird ein Vertrag über gemeinsame Verarbeitung geschlossen.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Widerruf Ihrer Einwilligung zur Datenverarbeitung</h3>
<p className="leading-relaxed text-white/60">Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Widerspruchsrecht gegen die Datenerhebung in besonderen Fällen sowie gegen Direktwerbung (Art. 21 DSGVO)</h3>
<div className="my-8 rounded-lg border border-signal-500/30 bg-signal-500/10 p-5">
<p className="mb-2 text-sm font-semibold uppercase tracking-wide text-signal-400">Wichtiger Hinweis · Widerspruchsrecht nach Art. 21 DSGVO</p>
<p className="text-sm leading-relaxed text-white/70">WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING. DIE JEWEILIGE RECHTSGRUNDLAGE, AUF DENEN EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE DIESER DATENSCHUTZERKLÄRUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN ÜBERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).</p>
<p className="mt-3 text-sm leading-relaxed text-white/70">WERDEN IHRE PERSONENBEZOGENEN DATEN VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, SO HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN; DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRECHEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).</p>
</div>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Beschwerderecht bei der zuständigen Aufsichtsbehörde</h3>
<p className="leading-relaxed text-white/60">Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Recht auf Datenübertragbarkeit</h3>
<p className="leading-relaxed text-white/60">Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Auskunft, Berichtigung und Löschung</h3>
<p className="leading-relaxed text-white/60">Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder Löschung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit an uns wenden.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Recht auf Einschränkung der Verarbeitung</h3>
<p className="leading-relaxed text-white/60">Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu können Sie sich jederzeit an uns wenden. Das Recht auf Einschränkung der Verarbeitung besteht in folgenden Fällen:</p>
<ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed text-white/60 marker:text-signal-500"><li>Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen Daten bestreiten, benötigen wir in der Regel Zeit, um dies zu überprüfen. Für die Dauer der Prüfung haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li><li>Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtmäßig geschah/geschieht, können Sie statt der Löschung die Einschränkung der Datenverarbeitung verlangen.</li><li>Wenn wir Ihre personenbezogenen Daten nicht mehr benötigen, Sie sie jedoch zur Ausübung, Verteidigung oder Geltendmachung von Rechtsansprüchen benötigen, haben Sie das Recht, statt der Löschung die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li><li>Wenn Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, muss eine Abwägung zwischen Ihren und unseren Interessen vorgenommen werden. Solange noch nicht feststeht, wessen Interessen überwiegen, haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li></ul>
<p className="mt-4 leading-relaxed text-white/60">Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschränkt haben, dürfen diese Daten – von ihrer Speicherung abgesehen – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Europäischen Union oder eines Mitgliedstaats verarbeitet werden.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">SSL- bzw. TLS-Verschlüsselung</h3>
<p className="leading-relaxed text-white/60">Diese Seite nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.</p>
<p className="mt-4 leading-relaxed text-white/60">Wenn die SSL- bzw. TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.</p>
</section>
<section id="datenerfassung" className="mt-16 scroll-mt-28 border-t border-white/10 pt-12">
<h2 className="font-mono text-2xl font-semibold text-signal-400">4. Datenerfassung auf dieser Website</h2>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Cookies</h3>
<p className="leading-relaxed text-white/60">Unsere Internetseiten verwenden so genannte „Cookies“. Cookies sind kleine Datenpakete und richten auf Ihrem Endgerät keinen Schaden an. Sie werden entweder vorübergehend für die Dauer einer Sitzung (Session-Cookies) oder dauerhaft (permanente Cookies) auf Ihrem Endgerät gespeichert. Session-Cookies werden nach Ende Ihres Besuchs automatisch gelöscht. Permanente Cookies bleiben auf Ihrem Endgerät gespeichert, bis Sie diese selbst löschen oder eine automatische Löschung durch Ihren Webbrowser erfolgt.</p>
<p className="mt-4 leading-relaxed text-white/60">Cookies können von uns (First-Party-Cookies) oder von Drittunternehmen stammen (sog. Third-Party-Cookies). Third-Party-Cookies ermöglichen die Einbindung bestimmter Dienstleistungen von Drittunternehmen innerhalb von Webseiten (z. B. Cookies zur Abwicklung von Zahlungsdienstleistungen).</p>
<p className="mt-4 leading-relaxed text-white/60">Cookies haben verschiedene Funktionen. Zahlreiche Cookies sind technisch notwendig, da bestimmte Webseitenfunktionen ohne diese nicht funktionieren würden (z. B. die Warenkorbfunktion oder die Anzeige von Videos). Andere Cookies können zur Auswertung des Nutzerverhaltens oder zu Werbezwecken verwendet werden.</p>
<p className="mt-4 leading-relaxed text-white/60">Cookies, die zur Durchführung des elektronischen Kommunikationsvorgangs, zur Bereitstellung bestimmter, von Ihnen erwünschter Funktionen (z. B. für die Warenkorbfunktion) oder zur Optimierung der Website (z. B. Cookies zur Messung des Webpublikums) erforderlich sind (notwendige Cookies), werden auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO gespeichert, sofern keine andere Rechtsgrundlage angegeben wird. Der Websitebetreiber hat ein berechtigtes Interesse an der Speicherung von notwendigen Cookies zur technisch fehlerfreien und optimierten Bereitstellung seiner Dienste. Sofern eine Einwilligung zur Speicherung von Cookies und vergleichbaren Wiedererkennungstechnologien abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage dieser Einwilligung (Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG); die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies für bestimmte Fälle oder generell ausschließen sowie das automatische Löschen der Cookies beim Schließen des Browsers aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalität dieser Website eingeschränkt sein.</p>
<p className="mt-4 leading-relaxed text-white/60">Sofern weitere Cookies und Dienste auf dieser Website eingesetzt werden, können Sie dies dieser Datenschutzerklärung entnehmen.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Einwilligung mit Usercentrics</h3>
<p className="leading-relaxed text-white/60">Diese Website nutzt die Consent-Technologie von Usercentrics, um Ihre Einwilligung zur Speicherung bestimmter Cookies auf Ihrem Endgerät oder zum Einsatz bestimmter Technologien einzuholen und diese datenschutzkonform zu dokumentieren. Anbieter dieser Technologie ist die Usercentrics GmbH, Sendlinger Straße 7, 80331 München, Website: <a href="https://usercentrics.com/de/" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://usercentrics.com/de/</a> (im Folgenden „Usercentrics“).</p>
<p className="mt-4 leading-relaxed text-white/60">Wenn Sie unsere Website betreten, werden folgende personenbezogene Daten an Usercentrics übertragen:</p>
<ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed text-white/60 marker:text-signal-500"><li>Ihre Einwilligung(en) bzw. der Widerruf Ihrer Einwilligung(en)</li><li>Ihre IP-Adresse</li><li>Informationen über Ihren Browser</li><li>Informationen über Ihr Endgerät</li><li>Zeitpunkt Ihres Besuchs auf der Website</li><li>Geolocation</li></ul>
<p className="mt-4 leading-relaxed text-white/60">Des Weiteren speichert Usercentrics ein Cookie in Ihrem Browser, um Ihnen die erteilten Einwilligungen bzw. deren Widerruf zuordnen zu können. Die so erfassten Daten werden gespeichert, bis Sie uns zur Löschung auffordern, das Usercentrics-Cookie selbst löschen oder der Zweck für die Datenspeicherung entfällt. Zwingende gesetzliche Aufbewahrungspflichten bleiben unberührt.</p>
<p className="mt-4 leading-relaxed text-white/60">Das Usercentrics-Banner auf dieser Website wurde mit Hilfe von eRecht24 konfiguriert. Das erkennen Sie daran, dass im Banner das Logo von eRecht24 auftaucht. Um das eRecht24-Logo im Banner auszuspielen, wird eine Verbindung zum Bildserver von eRecht24 hergestellt. Hierbei wird auch die IP-Adresse übertragen, die jedoch nur in anonymisierter Form in den Server-Logs gespeichert wird. Der Bildserver von eRecht24 befindet sich in Deutschland bei einem deutschen Anbieter. Das Banner selbst wird ausschließlich von Usercentrics zur Verfügung gestellt.</p>
<p className="mt-4 leading-relaxed text-white/60">Der Einsatz von Usercentrics erfolgt, um die gesetzlich vorgeschriebenen Einwilligungen für den Einsatz bestimmter Technologien einzuholen. Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. c DSGVO.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Auftragsverarbeitung</h4>
<p className="leading-relaxed text-white/60">Wir haben einen Vertrag über Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Server-Log-Dateien</h3>
<p className="leading-relaxed text-white/60">Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an uns übermittelt. Dies sind:</p>
<ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed text-white/60 marker:text-signal-500"><li>Browsertyp und Browserversion</li><li>verwendetes Betriebssystem</li><li>Referrer URL</li><li>Hostname des zugreifenden Rechners</li><li>Uhrzeit der Serveranfrage</li><li>IP-Adresse</li></ul>
<p className="mt-4 leading-relaxed text-white/60">Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Erfassung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an der technisch fehlerfreien Darstellung und der Optimierung seiner Website – hierzu müssen die Server-Log-Files erfasst werden.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Einsatz von KI auf der Website</h3>
<p className="leading-relaxed text-white/60">Wir nutzen KI-gestützte Dienste und / oder Anwendungen auf unserer Website.</p>
<p className="mt-4 leading-relaxed text-white/60">Wir setzen Künstliche Intelligenz (KI) auf unserer Website wie folgt ein:</p>
<p className="mt-4 leading-relaxed text-white/60">Verarbeitung und Automatisierung von Kontaktformular-Anfragen sowie Kundenanfragen mittels KI-Schnittstellen (OpenAI API / Make).</p>
<p className="mt-4 leading-relaxed text-white/60">Wenn Sie auf unserer Website mit Elementen interagieren oder in Berührung kommen, in denen künstliche Intelligenz zu Einsatz kommt (z. B. Chatbot), werden Ihre Eingaben inklusive Metadaten verarbeitet, um eine passende Antwort oder Reaktion zu generieren.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Nutzung dieser KI-gestützten Funktionen erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Wir haben ein berechtigtes Interesse daran, moderne Technologien auf unserer Website einzusetzen, um unsere Leistungen und Services zu verbessern und um neue Potenziale aus der Interaktion mit unseren Kunden zu erkennen. Falls eine Einwilligung erforderlich ist, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Ihre Einwilligung können Sie jederzeit widerrufen.</p>
<p className="mt-4 leading-relaxed text-white/60">Weitere Informationen zur Datenverarbeitung dieses Tools oder Dienstes erhalten Sie an der entsprechenden Stelle in dieser Datenschutzerklärung.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Einsatz von Künstlicher Intelligenz (KI) zur Beantwortung von Kundenanfragen</h3>
<p className="leading-relaxed text-white/60">Wir setzen KI-gestützte Software zur Bearbeitung und Beantwortung von Kundenanfragen ein. Dabei analysiert die von uns eingesetzte KI den Inhalt Ihrer Nachricht, um autonom oder teilweise autonom eine passende Antwort bzw. einen Antwortvorschlag zu generieren. In diesem Zusammenhang verarbeitet unsere KI sämtliche Inhalte Ihrer Nachricht, inklusive Namen, E-Mail-Adressen, Kommunikationsinhalte oder technische Informationen (z. B. IP-Adressen, Geräteinformationen).</p>
<p className="mt-4 leading-relaxed text-white/60">Die Verwendung der eingesetzten KI-Software erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Wir haben ein berechtigtes Interesse an einer möglichst effizienten Kundenkommunikation unter Einsatz moderner technischer Lösungen.</p>
<p className="mt-4 leading-relaxed text-white/60">Wir setzen folgende KI-Anwendungen ein:</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">ChatGPT</h4>
<p className="leading-relaxed text-white/60">Wir nutzen ChatGPT für unsere Kundenkommunikation. Anbieter ist die OpenAI, 3180 18th St, San Francisco, CA 94110, USA, <a href="https://openai.com" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://openai.com</a>. Wenn Sie also Kontakt zu uns aufnehmen, können Ihre Anfragen inklusive Metadaten an die Server von ChatGPT übertragen und dort verarbeitet werden, um eine passende Antwort zu generieren.</p>
<div className="my-6 rounded-lg border border-signal-500/30 bg-signal-500/10 p-5">
<p className="mb-2 text-sm font-semibold uppercase tracking-wide text-signal-400">Wichtiger Hinweis · Kein Modelltraining mit Ihren Daten</p>
<p className="text-sm leading-relaxed text-white/70">Wir haben ChatGPT so eingestellt, dass die von uns an ChatGPT weitergeleiteten Daten <strong className="text-white">nicht zum Trainieren des ChatGPT-Algorithmus</strong> eingesetzt werden.</p>
</div>
<p className="mt-4 leading-relaxed text-white/60">Weitere Informationen erhalten Sie hier: <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://openai.com/policies/privacy-policy</a>.</p>
<h5 className="font-mono mb-1.5 mt-4 text-sm font-semibold uppercase tracking-wide text-white/70">Auftragsverarbeitung</h5>
<p className="leading-relaxed text-white/60">Wir haben einen Vertrag über Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Make (Automatisierungs-Plattform)</h4>
<p className="leading-relaxed text-white/60">Wir nutzen Make (Automatisierungs-Plattform) für unsere Kundenkommunikation. Anbieter ist Celonis Inc. (Make), 1 World Trade Center, 87th Floor, New York, NY 10007, USA. Wenn Sie also Kontakt zu uns aufnehmen, können Ihre Anfragen inklusive Metadaten an die Server dieses Anbieters übertragen und dort verarbeitet werden, um eine passende Antwort zu generieren.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Anfrage per E-Mail, Telefon oder Telefax</h3>
<p className="leading-relaxed text-white/60">Wenn Sie uns per E-Mail, Telefon oder Telefax kontaktieren, wird Ihre Anfrage inklusive aller daraus hervorgehenden personenbezogenen Daten (Name, Anfrage) zum Zwecke der Bearbeitung Ihres Anliegens bei uns gespeichert und verarbeitet. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erfüllung eines Vertrags zusammenhängt oder zur Durchführung vorvertraglicher Maßnahmen erforderlich ist. In allen übrigen Fällen beruht die Verarbeitung auf unserem berechtigten Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen (Art. 6 Abs. 1 lit. f DSGVO) oder auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) sofern diese abgefragt wurde; die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Die von Ihnen an uns per Kontaktanfragen übersandten Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z. B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere gesetzliche Aufbewahrungsfristen – bleiben unberührt.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Hubspot CRM</h3>
<p className="leading-relaxed text-white/60">Wir nutzen Hubspot CRM auf dieser Website. Anbieter ist Hubspot Inc. 25 Street, Cambridge, MA 02141 USA (nachfolgend Hubspot CRM).</p>
<p className="mt-4 leading-relaxed text-white/60">Hubspot CRM ermöglicht es uns unter anderem, bestehende und potenzielle Kunden sowie Kundenkontakte zu verwalten. Mit Hilfe von Hubspot CRM sind wir in der Lage, Kundeninteraktionen per E-Mail, Social Media oder Telefon über verschiedene Kanäle hinweg zu erfassen, zu sortieren und zu analysieren. Die so erfassten personenbezogenen Daten können ausgewertet und für die Kommunikation mit dem potenziellen Kunden oder für Marketingmaßnahmen (z. B. Newslettermailings) verwendet werden. Mit Hubspot CRM sind wir ferner in der Lage, das Nutzerverhalten unserer Kontakte auf unserer Website zu erfassen und zu analysieren.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Verwendung von Hubspot CRM erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an einer möglichst effizienten Kundenverwaltung und Kundenkommunikation. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Details entnehmen Sie der Datenschutzerklärung von Hubspot: <a href="https://legal.hubspot.com/de/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://legal.hubspot.com/de/privacy-policy</a>.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Datenübertragung in die USA wird auf die Standardvertragsklauseln der EU-Kommission gestützt. Details finden Sie hier: <a href="https://www.hubspot.de/data-privacy/privacy-shield" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://www.hubspot.de/data-privacy/privacy-shield</a>.</p>
<p className="mt-4 leading-relaxed text-white/60">Das Unternehmen verfügt über eine Zertifizierung nach dem „EU-US Data Privacy Framework“ (DPF). Der DPF ist ein Übereinkommen zwischen der Europäischen Union und den USA, der die Einhaltung europäischer Datenschutzstandards bei Datenverarbeitungen in den USA gewährleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/5812" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://www.dataprivacyframework.gov/participant/5812</a>.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Auftragsverarbeitung</h4>
<p className="leading-relaxed text-white/60">Wir haben einen Vertrag über Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>
</section>
<section id="analyse-tools" className="mt-16 scroll-mt-28 border-t border-white/10 pt-12">
<h2 className="font-mono text-2xl font-semibold text-signal-400">5. Analyse-Tools und Werbung</h2>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Google Tag Manager</h3>
<p className="leading-relaxed text-white/60">Wir setzen den Google Tag Manager ein. Anbieter ist die Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.</p>
<p className="mt-4 leading-relaxed text-white/60">Der Google Tag Manager ist ein Tool, mit dessen Hilfe wir Tracking- oder Statistik-Tools und andere Technologien auf unserer Website einbinden können. Der Google Tag Manager selbst erstellt keine Nutzerprofile, speichert keine Cookies und nimmt keine eigenständigen Analysen vor. Er dient lediglich der Verwaltung und Ausspielung der über ihn eingebundenen Tools. Der Google Tag Manager erfasst jedoch Ihre IP-Adresse, die auch an das Mutterunternehmen von Google in die Vereinigten Staaten übertragen werden kann.</p>
<p className="mt-4 leading-relaxed text-white/60">Der Einsatz des Google Tag Managers erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an einer schnellen und unkomplizierten Einbindung und Verwaltung verschiedener Tools auf seiner Website. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Das Unternehmen verfügt über eine Zertifizierung nach dem „EU-US Data Privacy Framework“ (DPF). Der DPF ist ein Übereinkommen zwischen der Europäischen Union und den USA, der die Einhaltung europäischer Datenschutzstandards bei Datenverarbeitungen in den USA gewährleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/5780" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://www.dataprivacyframework.gov/participant/5780</a>.</p>
<h3 className="font-mono mb-2 mt-8 text-lg font-semibold text-white">Google Analytics</h3>
<p className="leading-relaxed text-white/60">Diese Website nutzt Funktionen des Webanalysedienstes Google Analytics. Anbieter ist die Google Ireland Limited („Google“), Gordon House, Barrow Street, Dublin 4, Irland.</p>
<p className="mt-4 leading-relaxed text-white/60">Google Analytics ermöglicht es dem Websitebetreiber, das Verhalten der Websitebesucher zu analysieren. Hierbei erhält der Websitebetreiber verschiedene Nutzungsdaten, wie z. B. Seitenaufrufe, Verweildauer, verwendete Betriebssysteme und Herkunft des Nutzers. Diese Daten werden dem jeweiligen Endgerät des Users zugeordnet. Eine Zuordnung zu einer User-ID erfolgt nicht.</p>
<p className="mt-4 leading-relaxed text-white/60">Des Weiteren können wir mit Google Analytics u. a. Ihre Maus- und Scrollbewegungen und Klicks aufzeichnen. Ferner verwendet Google Analytics verschiedene Modellierungsansätze, um die erfassten Datensätze zu ergänzen und setzt Machine-Learning-Technologien bei der Datenanalyse ein.</p>
<p className="mt-4 leading-relaxed text-white/60">Google Analytics verwendet Technologien, die die Wiedererkennung des Nutzers zum Zwecke der Analyse des Nutzerverhaltens ermöglichen (z. B. Cookies oder Device-Fingerprinting). Die von Google erfassten Informationen über die Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Nutzung dieses Dienstes erfolgt auf Grundlage Ihrer Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Die Einwilligung ist jederzeit widerrufbar.</p>
<p className="mt-4 leading-relaxed text-white/60">Die Datenübertragung in die USA wird auf die Standardvertragsklauseln der EU-Kommission gestützt. Details finden Sie hier: <a href="https://business.safety.google/adscontrollerterms/sccs/" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://business.safety.google/adscontrollerterms/sccs/</a>.</p>
<p className="mt-4 leading-relaxed text-white/60">Das Unternehmen verfügt über eine Zertifizierung nach dem „EU-US Data Privacy Framework“ (DPF). Der DPF ist ein Übereinkommen zwischen der Europäischen Union und den USA, der die Einhaltung europäischer Datenschutzstandards bei Datenverarbeitungen in den USA gewährleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/5780" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://www.dataprivacyframework.gov/participant/5780</a>.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">IP Anonymisierung</h4>
<p className="leading-relaxed text-white/60">Die Google Analytics IP-Anonymisierung ist aktiviert. Dadurch wird Ihre IP-Adresse von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum vor der Übermittlung in die USA gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Browser Plugin</h4>
<p className="leading-relaxed text-white/60">Sie können die Erfassung und Verarbeitung Ihrer Daten durch Google verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: <a href="https://tools.google.com/dlpage/gaoptout?hl=de" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://tools.google.com/dlpage/gaoptout?hl=de</a>.</p>
<p className="mt-4 leading-relaxed text-white/60">Mehr Informationen zum Umgang mit Nutzerdaten bei Google Analytics finden Sie in der Datenschutzerklärung von Google: <a href="https://support.google.com/analytics/answer/6004245?hl=de" target="_blank" rel="noopener noreferrer" className="text-signal-400 hover:text-signal-300 hover:underline">https://support.google.com/analytics/answer/6004245?hl=de</a>.</p>
<h4 className="font-mono mb-1.5 mt-5 text-base font-semibold text-white/85">Auftragsverarbeitung</h4>
<p className="leading-relaxed text-white/60">Wir haben mit Google einen Vertrag zur Auftragsverarbeitung abgeschlossen und setzen die strengen Vorgaben der deutschen Datenschutzbehörden bei der Nutzung von Google Analytics vollständig um.</p>
</section>
      </div>
    </main>
  );
}
